on:
 push:
   branches:
     - master




jobs:
 build:
  runs-on: ubuntu-latest


  steps:
    - name: 'Testing folder content'
      run: ls


    - uses: actions/checkout@v3
    - name: 'Testing folder content'
      run: ls

 